apiVersion: v1
kind: Pod

metadata:
  namespace: backend-ns
  name: tomcat-pod
  labels:
    apps: app-java
    
spec:
  containers:
  - name: container-tomcat
    image: tomcat
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"