apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    name: app
spec:
  containers:
  - name: liveness-container-test
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec: 
        command:
         - cat
         - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3