apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: myapp
spec:
  containers:
  - name: redis-container
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name:  "cache-storage"
      mountPath:  "/volumes"
  volumes:
    - name:  cache-storage
      emptyDir: {}

