apiVersion: v1
kind: Pod
metadata:
  name: redis-host-path-pod
  labels:
    name: myapp
spec:
  containers:
  - name: redis-host-path-container
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: "volumes"
      name: "volume-host-path"

  volumes:
  - name: "volume-host-path"
    hostPath:
      path:  "/var/lib/2-persist"
