apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  labels:
    app: myapplication
data:
  #connection database config
  database: mongodb
  database_uri: 127.0.0.0:27017

  #user interface
  font.title: Arial Bold
  background-color: red
  theme.1: clean
  theme.2: dark

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-env
  labels:
    name: myapp
spec:
  containers:
  - name: my-app
    image: nginx
    envFrom:
    - configMapRef:
        name:  my-configmap
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3030
