apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
  labels:
    app: myapplication
data:
  #connection database config
  database: mariadb
  database_uri: 127.0.0.0:27017

  #user interface
  font.title: Arial Bold
  background-color: red
  theme.1: clean
  theme.2: dark