apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-vol
  labels:
    name: myapp
spec:
  containers:
  - name: my-app
    image: nginx
    envFrom:
    - configMapRef:
        name:  my-cm
    volumeMounts:
      - name:  my-vol
        mountPath: "/etc/my-vol"
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name:  my-vol
      configMap:
        name:  my-cm