apiVersion: v1
kind: Secret
metadata:
  name:  my-secret
data:
  user: "YWRtaW4K"
  password: "YWRtaW5BZG1pbgo="
stringData:
  my-database-name: mariadbd
immutable: true
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-vol-env
  labels:
    type: pod-secret-vol-env
spec:
  containers:
  - name: my-app
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
    - secretRef:
        name:  my-secret
    volumeMounts:
      - name:  my-vol
        mountPath: "/etc/my-vol"
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name:  my-vol
      secret:
        secretName:  my-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    type: pod-secret-vol-env
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30001