apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-vol-env
  labels:
    name: myapp
spec:
  containers:
  - name: my-app
    image: nginx
    envFrom:
    - secretRef:
        name:  my-secret
        optional: true
    volumeMounts:
      - name:  my-vol
        mountPath: "/etc/my-vol"
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name:  my-vol
      secret:
        secretName:  my-secret
        optional: true