apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-dp
  namespace: jupyter
  labels:
    app: jupyter-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jupyter-app
  template:
    metadata:
      labels:
        app: jupyter-app
    spec:
      containers:
      - name:  jupyter-container
        image:  jupyter/minimal-notebook:python-3.10
        # image:  jupyter/minimal-notebook:2022-12-05
        ports:
        - containerPort: 8888
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"